---
# SAP Note: 2382421 - Optimizing the Network Configuration on HANA- and OS-Level
#
- name: Configure - Display SAP note number 2382421 and its version
  debug:
    msg: "SAP note {{ (__sap_hana_preconfigure_sapnotes_versions | selectattr('number', 'match', '^2382421$') | first).number }}
          (version {{ (__sap_hana_preconfigure_sapnotes_versions | selectattr('number', 'match', '^2382421$') | first).version }}): Recommended network settings for SAP HANA"

- name: Set kernel tunables as per SAP note 2382421
  block:

  - name: Modify entries in file '{{ __sap_hana_preconfigure_etc_sysctl_saphana_conf }}'
    lineinfile:
      path: "{{ __sap_hana_preconfigure_etc_sysctl_saphana_conf }}"
      create: yes
      mode: 0644
      regexp: ^{{ line_item.name }}.*
      line: "{{ line_item.name }}={{ line_item.value }}"
      state: present
    with_items: "{{ sap_hana_preconfigure_kernel_parameters }}"
    loop_control:
      loop_var: line_item

  - name: Reload kernel parameters from file '{{ __sap_hana_preconfigure_etc_sysctl_saphana_conf }}'
    command: sysctl -p "{{ __sap_hana_preconfigure_etc_sysctl_saphana_conf }}"
    register: __sap_hana_preconfigure_register_saphana_conf_sysctl_p_output

  - name: Print kernel parameters for network tuning
    debug:
      var: __sap_hana_preconfigure_register_saphana_conf_sysctl_p_output.stdout_lines

  when: sap_hana_preconfigure_config_all|d(true) or sap_hana_preconfigure_2382421|d(false)
