---
# tasks file for sap-hana-preconfigure: configuration

- debug:
    msg: "SAP note 2772999 Step 9: Configure Process Resource Limits"

- name: Set the hard limit for the max number of processes per user (nproc) to unlimited for group sapsys
  lineinfile:
    path: /etc/security/limits.d/99-sap.conf
    line: "@sapsys    hard    nproc    unlimited"
    state: present

- name: Set the soft limit for the max number of processes per user (nproc) to unlimited for group sapsys
  lineinfile:
    path: /etc/security/limits.d/99-sap.conf
    line: "@sapsys    soft    nproc    unlimited"
    state: present

- name: Set hard and soft limit for the max number of processes per user (nproc) to unlimited for the database group
  block:
    - name: Set hard limit for the max number of processes per user (nproc) to unlimited for the database group
      lineinfile:
        path: /etc/security/limits.d/99-sap.conf
        line: "@{{ sap_preconfigure_db_group_name }}    hard    nproc    unlimited"
        state: present

    - name: Set soft limit for the max number of processes per user (nproc) to unlimited for the database group
      lineinfile:
        path: /etc/security/limits.d/99-sap.conf
        line: "@{{ sap_preconfigure_db_group_name }}    soft    nproc    unlimited"
        state: present
  when:
    - sap_preconfigure_db_group_name is defined

...
