---
- name: create sapsys group
  group: name=sapsys gid={{ id_group_sapsys }}

- name: create sapadm user
  user:
    name: sapadm
    uid: "{{ id_user_sapadm }}"
    group: sapsys
    password: "{{ pw_user_sapadm_clear|password_hash('sha512') }}"

- name: install libtool-ltdl packages
  yum:
    state: latest
    name: libtool-ltdl


...
