---

- name: "Check if server is booted in BIOS or UEFI mode"
  stat:
    path: /sys/firmware/efi
    get_checksum: no
  register: efi_exists
  listen: __sap_hana_preconfigure_regenerate_grub2_conf_handler
  when:
    - sap_hana_preconfigure_run_grub2_mkconfig|d(true)

- debug:
    var: efi_exists.stat.exists
  listen: __sap_hana_preconfigure_regenerate_grub2_conf_handler
  when:
    - sap_hana_preconfigure_run_grub2_mkconfig|d(true)

- name: "Run grub-mkconfig (BIOS mode)"
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  register: command_result
  listen: __sap_hana_preconfigure_regenerate_grub2_conf_handler
  when:
    - not efi_exists.stat.exists
    - sap_hana_preconfigure_run_grub2_mkconfig|d(true)

- debug:
    var: command_result.stdout_lines, command_result.stderr_lines
  listen: __sap_hana_preconfigure_regenerate_grub2_conf_handler
  when:
    - not efi_exists.stat.exists
    - sap_hana_preconfigure_run_grub2_mkconfig|d(true)

- name: "Run grub-mkconfig (UEFI mode)"
  command: grub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg
  register: command_result
  listen: __sap_hana_preconfigure_regenerate_grub2_conf_handler
  when:
    - efi_exists.stat.exists
    - sap_hana_preconfigure_run_grub2_mkconfig|d(true)

- debug:
    var: command_result.stdout_lines, command_result.stderr_lines
  listen: __sap_hana_preconfigure_regenerate_grub2_conf_handler
  when:
    - efi_exists.stat.exists
    - sap_hana_preconfigure_run_grub2_mkconfig|d(true)

- name: Reboot the managed node
  reboot:
    test_command: /bin/true
  listen: __sap_hana_preconfigure_reboot_handler
  when:
    - sap_hana_preconfigure_reboot_ok|d(false)

- name: Let the role fail if a reboot is required
  fail:
    msg: Reboot is required!
  listen: __sap_hana_preconfigure_reboot_handler
  when:
    - sap_hana_preconfigure_fail_if_reboot_required|d(true)
    - not sap_hana_preconfigure_reboot_ok|d(false)

- name: Show a warning message if a reboot is required
  debug:
    msg: "WARN: Reboot is required!"
  listen: __sap_hana_preconfigure_reboot_handler
  when:
    - not sap_hana_preconfigure_fail_if_reboot_required|d(true)
    - not sap_hana_preconfigure_reboot_ok|d(false)

...
