---

- debug:
    msg: "imported RedHat/generic/assert-ksm.yml"

- name: Get info about file /etc/init.d/boot.local
  stat:
    path: /etc/init.d/boot.local
  register: __stat_boot_local

- name: Assert that file /etc/init.d/boot.local exists
  assert:
    that: __stat_boot_local.stat.exists
    fail_msg: "FAIL: File /etc/init.d/boot.local does not exist!"
    success_msg: "PASS: File /etc/init.d/boot.local exist."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

- name: Assert that file /etc/init.d/boot.local is a regular file
  assert:
    that: __stat_boot_local.stat.isreg
    fail_msg: "FAIL: File /etc/init.d/boot.local is not a regular file!"
    success_msg: "PASS: File /etc/init.d/boot.local is a regular file."
  ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors|d(false) }}"
  when: __stat_boot_local.stat.exists

- name: Assert that the mode of file /etc/init.d/boot.local is 0755
  assert:
    that: "__stat_boot_local.stat.mode == '0755'"
    fail_msg: "FAIL: File /etc/init.d/boot.local has mode '{{ __stat_boot_local.stat.mode }}' but the expected mode is '0755'!"
    success_msg: "PASS: File /etc/init.d/boot.local has mode 0755."
  ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors|d(false) }}"
  when: __stat_boot_local.stat.exists

- name: Get KSM setting in /etc/init.d/boot.local
  command: awk '/ksm/{print}' /etc/init.d/boot.local
  register: __boot_local_ksm_result
  ignore_errors: true
  changed_when: no
  when: __stat_boot_local.stat.exists

- name: Assert that ksm is disabled in /etc/init.d/boot.local
  assert:
    that: "'echo 0 > /sys/kernel/mm/ksm/run' in __boot_local_ksm_result.stdout"
    fail_msg: "FAIL: The line 'echo 0 > /sys/kernel/mm/ksm/run' is not in file /etc/init.d/boot.local!"
    success_msg: "PASS: The line 'echo 0 > /sys/kernel/mm/ksm/run' is in file /etc/init.d/boot.local."
  ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors|d(false) }}"
  when: __stat_boot_local.stat.exists

- name: Get status of KSM
  command: cat /sys/kernel/mm/ksm/run
  register: __ksm_running_result
  ignore_errors: true
  changed_when: no

- name: Assert that ksm is disabled in /etc/init.d/boot.local
  assert:
    that: "__ksm_running_result.stdout == '0'"
    fail_msg: "FAIL: KSM is currently enabled but it needs to be disabled!"
    success_msg: "PASS: KSM is disabled currently."
  ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors|d(false) }}"

...
