---

- debug:
    msg: "imported RedHat/generic/assert-cpu-governor-for-performance.yml"

# can be configured by tuned profile sap-hana, entry "governor=performance"
#   in included tuned profile throughput-performance
- block:
    - name: Check if system is able to set CPU Governor for performance (x86_64 platform only)
      command: bash -lc "LC_ALL=C cpupower frequency-info -g | awk '/available cpufreq governors/{print $(NF-1), $NF}'"
      check_mode: no
      register: __cpupower_frequency_result
      ignore_errors: true
      changed_when: no

    - debug:
        var: __cpupower_frequency_result.stdout_lines, __cpupower_frequency_result.stderr_lines

    - name: Check that the CPU Governor for performance is configured (x86_64 platform only)
      block:
        - name: Get info about file /etc/rc.d/rc.local
          stat:
            path: /etc/rc.d/rc.local
          register: __stat_rc_local

        - name: Assert that file /etc/rc.d/rc.local exists (x86_64 platform only)
          assert:
            that: __stat_boot_local.stat.exists
            fail_msg: "FAIL: File /etc/rc.d/rc.local does not exist!"
            success_msg: "PASS: File /etc/rc.d/rc.local exist."
          ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors|d(false) }}"

        - name: Assert that file /etc/rc.d/rc.local exists (x86_64 platform only)
          assert:
            that: __stat_rc_local.stat.isreg
            fail_msg: "FAIL: File /etc/rc.d/rc.local is not a regular file!"
            success_msg: "PASS: File /etc/rc.d/rc.local is a regular file."
          ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors|d(false) }}"
          when: __stat_rc_local.stat.exists

        - name: Assert that the mode of file /etc/rc.d/rc.local is 0644 (x86_64 platform only)
          assert:
            that: "__stat_rc_local.stat.mode == '0644'"
            fail_msg: "FAIL: File /etc/rc.d/rc.local has mode '{{ __stat_rc_local.stat.mode }}' but the expected mode is '0644'!"
            success_msg: "PASS: File /etc/rc.d/rc.local has mode 0644."
          ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors|d(false) }}"
          when: __stat_rc_local.stat.exists

        - name: Get the contents of file /etc/rc.d/rc.local (x86_64 platform only)
          command: grep cpupower /etc/rc.d/rc.local
          register: __rc_local_cpupower_result
          changed_when: no
          ignore_errors: yes
          when: __stat_rc_local.stat.exists

        - name: Assert that CPU Governor for performance is configured at boot time (x86_64 platform only)
          assert:
            that: "__rc_local_cpupower_result.stdout == 'cpupower frequency-set -g performance'"
            fail_msg: "FAIL: The CPU Governor for performance is not configured at boot time!"
            success_msg: "PASS: CPU Governor for performance is configured at boot time."
          ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors|d(false) }}"

        - name: Get the current status of the CPU Governor for performance (x86_64 platform only)
          command: cpupower frequency-info -g
          register: __cpupower_result
          changed_when: no
          ignore_errors: yes

        - debug:
            var: __cpupower_result.stdout_lines

        - name: Assert that the current status of the CPU Governor for performance is performance (x86_64 platform only)
          assert:
            that: "'performance' in __cpupower_result.stdout_lines"
            fail_msg: "FAIL: The current status of the CPU Governor for performance is not 'performance'!"
            success_msg: "PASS: The current status of the CPU Governor for performance is 'performance'."
          ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors|d(false) }}"

      when: "__cpupower_frequency_result.stdout != 'Not Available'"

    - debug:
        msg: "INFO: The system is not capable of setting the CPU Governor for 'performance'."
      when: "__cpupower_frequency_result.stdout == 'Not Available'"

  when: ansible_architecture == 'x86_64' and
        (not sap_hana_preconfigure_use_tuned or
           sap_hana_preconfigure_assert_all_config
        )

...
