---

- debug:
    msg: "imported RedHat/generic/assert-tsx.yml"

- block:
    - name: Get contents of GRUB_CMDLINE_LINUX in /etc/default/grub
      command: grep GRUB_CMDLINE_LINUX /etc/default/grub
      register: __sap_hana_preconfigure_register_default_grub_cmdline_tsx_assert
      changed_when: no

    - name: Assert that tsx=on is in GRUB_CMDLINE_LINUX in /etc/default/grub
      assert:
        that: "'tsx=on' in __sap_hana_preconfigure_register_default_grub_cmdline_tsx_assert.stdout"
        fail_msg: "FAIL: 'tsx=on' is not in GRUB_CMDLINE_LINUX in /etc/default/grub!"
        success_msg: "PASS: 'tsx=on' is in GRUB_CMDLINE_LINUX in /etc/default/grub."
      ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors|d(false) }}"

    - name: Get contents of /proc/cmdline
      command: cat /proc/cmdline
      register: __sap_hana_preconfigure_register_proc_cmdline_tsx_assert
      changed_when: no

    - name: Assert that tsx=on is in /proc/cmdline
      assert:
        that: "'tsx=on' in __sap_hana_preconfigure_register_proc_cmdline_tsx_assert.stdout"
        fail_msg: "FAIL: 'tsx=on' is not in /proc/cmdline!"
        success_msg: "PASS: 'tsx=on' is in /proc/cmdline."
      ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors|d(false) }}"

# We are counting the number of cpuinfo lines which contain "flags" and subtracting those lines
#   which contain "flags" and " rtm ". If the result is 0, all CPUs contain flag "rtm".
    - name: Get rtm status of all CPUs
      shell: awk '$1=="flags"{n++}$1=="flags"&&$0~" rtm" {a++}END{print n-a}' /proc/cpuinfo
      register: __sap_hana_preconfigure_register_cpuinfo_flags_contain_rtm
      changed_when: no

    - name: Assert that all CPUs contain flag rtm
      assert:
        that: "__sap_hana_preconfigure_register_cpuinfo_flags_contain_rtm.stdout == '0'"
        fail_msg: "FAIL: At least one of the CPUs does not contain flag 'rtm'!"
        success_msg: "PASS: All CPUs contain flag 'rtm'."
      ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors|d(false) }}"

  when: ansible_architecture == 'x86_64' and
        ansible_distribution == 'RedHat' and
        ansible_distribution_major_version == '8' and
        __sap_hana_preconfigure_fact_ansible_distribution_minor_version >= '3'
