---

- debug:
    msg: "imported RedHat/generic/assert-abrt-ccpp.yml"

- name: Disable abrt-ccpp if installed, and get status of abrt-ccpp
  block:
    - name: Get status of abrt-ccpp
      command: systemctl status abrt-ccpp
      register: __sap_hana_preconfigure_register_abrt_ccpp_status_assert
      ignore_errors: yes
      changed_when: no

    - name: Assert that abrt-ccpp is disabled
      assert:
        that: "'/usr/lib/systemd/system/abrt-ccpp.service; disabled' in __sap_hana_preconfigure_register_abrt_ccpp_status_assert.stdout"
        fail_msg: "FAIL: Service 'abrt-ccpp' is not disabled!"
        success_msg: "PASS: Service 'abrt-ccpp' is disabled."
      ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors|d(false) }}"

    - name: Assert that abrt-ccpp is inactive
      assert:
        that: "'inactive (dead)' in __sap_hana_preconfigure_register_abrt_ccpp_status_assert.stdout"
        fail_msg: "FAIL: Service 'abrt-ccpp' is active!"
        success_msg: "PASS: Service 'abrt-ccpp' is inactive."
      ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors|d(false) }}"

  when: "'abrt-ccpp' in ansible_facts.packages"

- debug:
    msg: "PASS: Package 'abrt-ccpp' is not installed."
  when: "'abrt-ccpp' not in ansible_facts.packages"
