---

- debug:
    msg: "imported RedHat/generic/assert-firewalld.yml"

- name: Assert that service firewalld is disabled, and inactive or stopped
  include_tasks: assert-services.yml
  vars:
    line_item: firewalld
