---

- debug:
    msg: "imported RedHat/generic/configure-c-states-for-lower-latency.yml"

# can be configured by tuned profile sap-hana, entry "force_latency=70"
- name: Configure C-States for lower latency
  lineinfile:
    path: /etc/default/grub
    backup: yes
    backrefs: yes
    state: present
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.* {{ line_item }}).*). *$'
    line: "\\1 {{ line_item }}\""
  with_items:
    - "processor.max_cstate=1"
    - "intel_idle.max_cstate=1"
  notify: "Regenerate grub2 conf handler"
  when:
    - ansible_architecture == 'x86_64'
    - sap_hana_preconfigure_modify_grub_cmdline_linux
  tags: grubconfig
  loop_control:
    loop_var: line_item

...
