---

- debug:
    msg: "imported RedHat/generic/disable-coredumps.yml"

- name: Create file /etc/security/limits.d/99-sap.conf if it does not exist
  file:
    path: /etc/security/limits.d/99-sap.conf
    state: touch
    mode: 0644

- name: Disable core file creation for all users, hard limit
  lineinfile:
    path: /etc/security/limits.d/99-sap.conf
    line: "hard core 0"
    state: present

- name: Disable core file creation for all users, soft limit
  lineinfile:
    path: /etc/security/limits.d/99-sap.conf
    line: "soft core 0"
    state: present

...
