---

- debug:
    msg: "imported RedHat/generic/configure-firewall.yml"

- name: Stop and disable service firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  when: "'firewalld' in ansible_facts.packages"

- name: Get status of firewalld
  command: systemctl status firewalld
  register: __sap_hana_preconfigure_register_firewalld_status
  ignore_errors: True
- debug:
    var: __sap_hana_preconfigure_register_firewalld_status.stdout_lines, __sap_hana_preconfigure_register_firewalld_status.stderr_lines
