---

- debug:
    msg: "imported RedHat/generic/disable-coredumps.yml"

- name: Disable core file creation for all users
  lineinfile:
    path: /etc/security/limits.d/99-sap.conf
    create: yes
    regexp: '^\*\s+{{ line_item }}\s+core\s.*'
    line: "*\t{{ line_item }}\tcore\t0"
  with_items:
    - hard
    - soft
  loop_control:
    loop_var: line_item
