---

- debug:
    msg: "imported RedHat/generic/disable-abrt.yml"

- name: Check if abrt is installed
  package:
    name: abrt
    state: present
  check_mode: true
  register: __sap_hana_preconfigure_register_abrt_installed
  ignore_errors: yes
- debug:
    var: __sap_hana_preconfigure_register_abrt_installed

- name: Disable abrtd if installed, and get status of abrtd
  block:
    - name: Disable abrtd if installed
      systemd:
        name: abrtd
        state: stopped
        enabled: no
      when: not __sap_hana_preconfigure_register_abrt_installed.changed

    - name: Get status of abrt
      command: systemctl status abrtd
      register: __sap_hana_preconfigure_register_abrt_status
      ignore_errors: true
    - debug:
        var: __sap_hana_preconfigure_register_abrt_status.stdout_lines, __sap_hana_preconfigure_register_abrt_status.stderr_lines

  when: not __sap_hana_preconfigure_register_abrt_installed.changed

...
