---

- debug:
    msg: "imported RedHat/generic/enable-tsx.yml"

- name: Enable TSX at boot time
  lineinfile:
    path: /etc/default/grub
    backup: yes
    backrefs: yes
    state: present
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.* {{ line_item }}).*). *$'
    line: "\\1 {{ line_item }}\""
  with_items:
     - "tsx=on"
  notify: __sap_hana_preconfigure_regenerate_grub2_conf_handler
  when:
    - ansible_architecture == 'x86_64'
    - ansible_distribution == 'RedHat'
    - ansible_distribution_major_version == '8'
    - __sap_hana_preconfigure_fact_ansible_distribution_minor_version >= '3'
  tags: grubconfig
  loop_control:
    loop_var: line_item
