---
# tasks file for sap-preconfigure: configuration

# 06-configure-c-states-for-lower-latency.yml
- debug:
    msg: "SAP note 2777782 Step 6: Configure C-States for lower latency"
- name: "Configure C-States for lower latency"
  lineinfile:
    path: /etc/default/grub
    backup: yes
    backrefs: yes
    state: present
    regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT=(?!.* {{ line_item }}).*). *$'
    line: "\\1 {{ line_item }}\""
  with_items:
     - "processor.max_cstate=1"
     - "intel_idle.max_cstate=1"
  notify: regenerate grub2 conf
  when: ansible_architecture == "x86_64" and
        ansible_os_family == 'RedHat' and
        ansible_distribution_major_version == '8'
  tags: grubconfig
  loop_control:
    loop_var: line_item

...
