---
# tasks file for sap-hana-preconfigure: configuration

# 08-configure-epb.yml
# configured by tuned profile sap-hana, entry "energy_perf_bias=performance"
#   in included tuned profile throughput-performance
- debug:
    msg: "SAP note 2777782 Step 8: Configure Energy Performance Bias (EBP, x86_64 platform only)"
- block:
    - name: Check if system supports Intel's performance bias setting
      command: bash -lc "cpupower info | head -1 | awk '{print $2, $3, $4}'"
      register: command_check_result
      ignore_errors: true
      changed_when: false
    - debug:
        var: command_check_result.stdout_lines, command_check_result.stderr_lines

    - name: Change EBP if possible
      block:
        - name: Create file /etc/init.d/boot.local if it does not exist
          file:
            path: /etc/rc.d/rc.local
            state: touch
            mode: 0644

        - name: Configure EBP at boot time
          lineinfile:
            dest: /etc/init.d/boot.local
            line: cpupower set -b 0

        - name: Configure EBP on the running system
          command: bash -lc "cpupower set -b 0"
          register: command_result
        - debug:
            var: command_result.stdout_lines, command_result.stderr_lines

        - name: Get status of EBP
          command: bash -lc "cpupower info"
          register: command_result
          ignore_errors: true
          changed_when: false
        - debug:
            var: command_result.stdout_lines, command_result.stderr_lines

      when:
       - command_check_result.stdout != 'does not support'

  when:
    - ansible_architecture == 'x86_64'
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '8'
    - not sap_hana_preconfigure_use_tuned_where_possible

...
