---

- debug:
    msg: "SAP note 2777782 Step 10: Increase kernel.pid_max"

- name: Set kernel parameter kernel.pid_max to 4194304
  lineinfile:
    path: /etc/sysctl.d/sap.conf
    create: yes
    regexp: ^kernel.pid_max.*
    line: 'kernel.pid_max=4194304'
    state: present

- name: Reload kernel parameters from file '/etc/sysctl.d/sap.conf'
  command: sysctl -p /etc/sysctl.d/sap.conf
  register: __sap_hana_preconfigure_register_sap_conf_sysctl_p_output

- name: Print kernel parameters after setting kernel.pid_max
  debug:
    var: __sap_hana_preconfigure_register_sap_conf_sysctl_p_output.stdout_lines
