---

#- name: Enable Debugging
#  debug:
#    verbosity: "{{ debuglevel }}"
#
- name: list of required SAP Notes
  debug: 
    var: sap_hana_preconfigure_sapnotes | difference([''])

- name: include configuration actions for required sapnotes 
  include_tasks: "sapnotes/{{ item }}/installation.yml"
  with_items: "{{ sap_hana_preconfigure_sapnotes | difference(['']) }}"
     
...
